# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockGrowEvent.html
BlockGrowEvent: false

# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockSpreadEvent.html
BlockSpreadEvent: false

# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/world/StructureGrowEvent.html
StructureGrowEvent: false

BlockFormEvent: false

EntityBlockFormEvent: false